version: '2.0'
services:
   monitor:
      image: buythewhale/ethstats_monitor
      volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
   dashboard:
      image: buythewhale/ethstats
      volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
      ports:
      - 3001:3000
